language: java
script:
- mvn clean
- mvn install -DskipTests=true
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: TafdAdN2SrnwHnTSa4O2wKEKoZGomJfdcYrOixmnn1/B4iTk/wLH67trFPtEIaEvxMC4q8zGbXe+hJWa7RQBX6Uyatm8+43gMr7H4l3m2bV6a8enFz+kkBow9JRwBpXMlRikXQ4raEu9t8yy5DZ7XWPUTYws8NyqeliRXeF2xStVK+m1JJo5x3aTss+CFyq5m78tEwHsGqQeiN7gq5la3o8immVYN9rERVBOsmuHuV97vYli311SlFjazmKvixtNMbIJo81ZnHHUI/mQXktyK4H97rHOnM6bslIL78VRQ6Hzf/CC+7kL0zcWvWUxJCpNiAYoph1SR0ZrI1BxnToy1ZBIB4VQno6XjTwE5aR/85JbBwzMqKmOBtXaLRxa8q3Bnh1YbA9tHwDEGgLBu4evWAhYOrZPJQfeHRez7XjBbzadXABUXK0RHMn5rqs3KXwEI3l6Db3Qw08RtLUTQFbjpNtr7Dx7B4zju6DjSwcTKngzbKH5TObGraFQcvhBBg8qfo0aDd3vTf4BZVXyn9YkAiFAOk/EiK66oKTAtq+PHz9bCdsECqY3BHS+doptNomDCBcedUNNVe4o6zD81Q6fA9fr5AoeevFiGMNe8gpvXm2YIJPBmmvVHnxYyEVlLVUUM1RYMVo6CY5CQ7Fjua3eshgaoUswrDRq4P3WqE53Qdw=
  on: master