language: java
script:
- mvn clean
- mvn install -DskipTests=true
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: sGM526FL/6OBx9uijTVy4v0sCeyBNOzwBvWyglrZFSGTuS5dxM1MSULl66zqAn745d2FD7qiHC/uBV+mD1JZNwfvyU3d42I9P5tdlItyworEjZKfSWrk488nRVGP2hNp6wn68aDnP+z4xWGiZKVIVx2ClQ+ngLCqD/AwHBc+Uykxnp27hnraXuljsr9wzf8b+rMq4GpuchxzTSX1S6nrv3WzjLs8oX/7h0sc2jGQocBUToICX7nlqpYhYME/fEpy5/sz07iHXntU0HTdRP+/62k6jQ8YCqwah91EOvaaae/KKL/IN9Cs9fo8K8zQogca+iU+ABY6QCmAhm0mHpqzJ24zq4pvK7stA4c8QFbq+0m0deRQxUhvy+qnu3JUQrgAiuVctT9Q+GbbqLgdCFgGQbzYzCWCbvnBMF7yDv6ZPfIkSD/QUcxRgUZBNxz2WMBOad1Ng2mvHI4vwHOSBbwL5ZbX/e1LlTPdRoxHCrquCoM4ocXICjNt+2FrnQW/zuiAwZF35DzwgW9Ny//tAnV3Gp82SeFxp3Vek4XFPjeNAPwGDpUxiCYcwSHXFi04sNgdWpJuYRl4coqJZ3rvkI68k15B9Yp8zuHdByfMtAsxZHUy/oBD8pmIbqINqLXFjBDST31ESCu1BeQ7wxWk1+M0gCh3zdaQ/EHHj2Cgjxsrvaw=
  app: service-webapp
  on: master