language: java
script:
- mvn clean
- mvn install -DskipTests=true
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: ctySmW/LlgywCmO0DwRDFpAqQHi3pH2vepPmASLjau7POoFaVJ2dIGnmIZ3afvaCRdC1vUYw6dUq5+/1nSDuUTP+Ib5tA01zrYK1KiWTVkV01RP4e04pykDyEvNuY+8mMj3vLq4gKF6EpnhsCBrlzWlCPmny8v7g4cBkrlvzADRO9rcuqpzf8dgmcG8K9K90tIdNK2KkbK7Vwcp0mWnvNv5ntWKaJ1ZQSHcHPBFr8m4+FNUdSQAMCab9M9mgoX5+hJEWWjT6gCnVUVoMjhb+RdNZMmbDwmzApny/jSEIpeuuIQ3XidrYhSkKjxOyYQ6OhvPfa8WpY7lMkeTH4gA18J+y7TuyA3WNPosJDNzqrCMw2RbUK+Q7dCRlmVoDiA5wP5gSy47n/jl94cctZUsmPZlHPddeEVy2sqjaUt+YOcf2wZ+Dlu6wOhDVgGI+ojYhwUDjybSdCKAfIsqHc4JIiyu3I5kyjdlC+s2yN0oY2/wOHV5WcMJIs1rqsRPuuPcQbnq/Be9EOUCH+C/GSRr7TwF29nHRzJJ6+MphG9Gn/XOG/OZQzpVh3yDGYbXrywbEIkbmrC8RW/wyw+BhhJljl8liJ1edzVRcLuya/nGMo9lWPx59M/um7WEWrGFTwwGBJU2Hu/fTuJQ2xJsXvYYEf19g1mjv0Ro+OMDyCjv55PI=
  app: 'service-webapp'
  on:
    repo: zalokhan/ServiceWebApp
